### ISSUE TITLE
Error "cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by ts-web** [danactive/grunt-tfs-unlock#4]
I am using ```node v0.10.35``` and ```grunt-tfs-unlock v0.2.0```.

My gruntfile has ```grunt.loadNpmTasks('grunt-tfs-unlock');``` and this configuration:

    "tfs-unlock": {
      js: {
        //tfsPath: ['vs2013', 'bit32'],
        tfsPath: 'C:/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE',
        files: {
          src: [
            scripts+'*.min.js'
          ]
        }
      }
    },

Running ```grunt tfs-unlock -v``` Yields this output:

    Running "tfs-unlock:js" (tfs-unlock) task
    Verifying property tfs-unlock.js exists in config...OK
    Files: scripts/common.min.js, ... , scripts.layout.min.js -> src
    Options: (none)
    Warning: Cannot read property '0' of undefined Use --force to continue.
    
    Aborted due to warnings

Any suggestions? Am I doing something wrong?

**Comment by danactive** [comment]
Sorry ts, I can only guess on this error, perhaps you are referencing missing files. Apply nonull: true (http://stackoverflow.com/a/26982696) to your task, this will warning if the paths are incorrect.

**Comment by danactive** [comment]
FYI: Error handle as been improved with v0.3.2

**Comment by hazzik** [comment]
The problem is with tfsPath itself. It should be ['vs2013', 'bit64'] in that case, or should be empty.
