### ISSUE TITLE
Random failures

### ISSUE THREAD

**Issue by danwellman** [danactive/grunt-tfs-unlock#7]
I'm using this plugin to TFS-unlock a couple of CSS files. Mostly the plugin works as expected, but occasionally, it fails with a message in the command line:

>  Running "tfs-unlock:checkoutCss" (tfs-unlock) task
> \>\> Child process exited with code # 100.

Code 100 according to MSDN docs is "Nothing succeeded"

It's weird because I'll get that error, run the exact same command again (which uses the same task, same config) and the second time it succeeds.

My task configuration is as follows:

    tfs-unlock': {
        checkoutCss: {
            options: {
                action: 'checkout'
            },
            files: {
                src: [
                    'root/css/myStyles.css',
                    'root/css/shared.css'
                ]
            }
        }
    },

Mostly it works fine, I'd say failure rate is maybe 1 in 10 times

**Comment by danactive** [comment]
What is your node version? (`node -v` in terminal) and operating system version?

**Comment by danwellman** [comment]
Sorry for delay, this is happening on my work machine...

Node version is: v0.12.7
OS is: Windows 7 Pro

**Comment by danwellman** [comment]
Any news..?

**Comment by danactive** [comment]
I'm currently on a Mac, so I'm unable to test but try passing `tfsPath` to the options

**Comment by danwellman** [comment]
Ok will do, thanks

**Comment by danwellman** [comment]
The `tfsPath` option didn't seem to make a difference, but setting the `wait` option does seem to have fixed the issue :)
